# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('travelStart', models.CharField(max_length=200)),
                ('travelEnd', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allusertrips', models.ManyToManyField(related_name='usersontrips', to='bestLogin.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestLogin.User')),
            ],
            managers=[
                ('tManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
